CREATE TABLE nutrition (
    NutritionID INT PRIMARY KEY,
    RecipeID INT,
    Name VARCHAR(50),
    Amount DECIMAL(10, 5),
    Unit VARCHAR(10),
    CreatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    ModifiedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (RecipeID) REFERENCES Recipes(RecipeID)
);