CREATE TABLE recipes (
    RecipeID INT PRIMARY KEY,
    RecipeName VARCHAR(255),
    ImageID VARCHAR(255),
    Ingredients VARCHAR(10),
    CreatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    ModifiedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);